name: Build Windows executable

on:
  push:
    tags:
      - 'v*'  # Triggers only on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed --icon=icon.ico voice_assistant_new_ui.py

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .exe to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/voice_assistant_new_ui.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
